import Head from 'next/head'

// sections
import Hero from '@/sections/Hero'
import Footer from '@/components/Footer'
import Nosotros from '@/sections/Nosotros'
import Elegirnos from '@/sections/Elegirnos'
import Preguntas from '@/sections/Preguntas'
import Consultas from '@/sections/Consultas'
import Membresias from '@/sections/Membresias'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Ludena Landing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Nosotros />
      <Membresias />
      <Elegirnos />
      <Preguntas />
      <Consultas />
      <Footer />
    </div>
  )
}

export default Home
